name: 'zkg install'
description: 'Install a Zeek package via zkg.'
inputs:
  pkg:
    description: 'The name, URL, or path of the package to install'
    required: false
    default: '.'
  pkg_version:
    description: 'Zeek package version to use'
    required: false
    default: ''
  pkg_sysdeps:
    description: 'Additional Debian system packages to install'
    required: false
    default: ''
  pkg_uservars:
    description: 'User variables to define for the package build'
    required: false
    default: ''
  zeek_version:
    description: 'Zeek version (zeek/zeek-lts/zeek-nightly/zeek-X.Y, from the OBS builds)'
    required: false
    default: 'zeek'
  load_packages:
    description: 'After successful package install, launch Zeek to load package(s).'
    required: false
    default: 'no'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--pkg'
    - ${{ inputs.pkg }}
    - '--pkg-version'
    - ${{ inputs.pkg_version }}
    - '--pkg-sysdeps'
    - ${{ inputs.pkg_sysdeps }}
    - '--pkg-uservars'
    - ${{ inputs.pkg_uservars }}
    - '--zeek-version'
    - ${{ inputs.zeek_version }}
    - '--load-packages'
    - ${{ inputs.load_packages }}
